#!/usr/bin/env python

import sys

time_ns = float(sys.argv[1].replace(",", ""))
time_s = time_ns * 1e-9

n_elements = 200_000_000
type_size_bytes = 4
operations = 3
data = n_elements * type_size_bytes * operations / 1024 / 1024 / 1024

print(data / time_s)
